name: Build and Deploy

on:
  push:
    branches:
      - main  # Cambia esto al nombre de tu rama principal si es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18  # Puedes cambiar la versión de Node.js según tus requisitos

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
      
    - name: ssh scp ssh pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        WELCOME: "ssh scp ssh pipelines"
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        pass: ${{ secrets.SSH_PASSWORD }}
        connect_timeout: 10s
        first_ssh: |
          rm -rf /home/dh_3zbtvf/nobordersbigjazz.com/github
          ls -la  \necho $WELCOME 
          mkdir -p /home/dh_3zbtvf/nobordersbigjazz.com/github && 
          mkdir -p /home/dh_3zbtvf/nobordersbigjazz.com/github2 &&
        scp: |
          './dish/*' => /home/dh_3zbtvf/nobordersbigjazz.com/github
        last_ssh: |
          echo $LASTSSH && 
          (mkdir /home/dh_3zbtvf/nobordersbigjazz.com/github || true)
          || ls -la

